# Generated by Django 3.2.8 on 2021-10-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.
            CharField(
                max_length=100,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='is_bestselling',
            field=models.
            BooleanField(
                default=False
            ),
        ),
    ]
